version: '3'
services:
  backend:
    build:
      context: FlowBackend/
      dockerfile: DockerFile
    container_name: dataflow-backend
    ports:
      - 5001:5001
  frontend:
    build: 
      context: FlowFrontend/
      dockerfile: Dockerfile
    container_name: dataflow-frontend
    ports:
      - 4200:8080